name: flutter_poc_min
description: A new Flutter project.
publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Default Flutter icons
  cupertino_icons: ^1.0.2

  # Your project’s dependencies (already detected)
  flutter_secure_storage: ^9.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints for better code practices
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
